### ISSUE TITLE
Checkpoint one ready

### ISSUE THREAD

**Issue by Kgrau1** [Kgrau1/IndieProjectForKG#1]
@pawaitemadisoncollege Checkpoint 1 is ready in the checkpoints folder.

**Comment by pawaitemadisoncollege** [comment]
Hi Kevin! Here are my findings from a review of checkpoint 1:

**Problem statement** answers the question "what problem will this solve and how?". Good!

- [ ] Should be placed on the homepage (readme.md) of your repository. This is the first thing anyone viewing your repo will see, so it's important to give details here.

**User stories** Are well-written to clearly describe the user and the thing they want be able to do.

- [ ] This list is best placed in its own file and linked from the readme.md. Again, consider a prospective employer reviewing this - make it easy for them to find everything. 
- [ ] No need for the checkpoint folder.
- [ ] If you want to organize documents like these, something like a "design" or "planning" directory would make more sense to anyone who is not part of this class. 
- [ ] For MVP, I would recommend implementing either the employee user stories or only the administrator user stories.
- [ ] Whichever user stories series you choose from above, make sure there are stories that cover CRUD and authentication. Mark these as MVP in some way. Everything else will be a stretch goal for this semester. 

**Project plan** a good start!

- [ ] Next steps are to put this in its own file for the reasons listed previously.
- [ ] Detail out the target dates for this work. You can always move things around, but this should help you see the complete body of work.
- [ ] Add each MVP story to the plan. Then, add the smaller tasks that make up that story. 

**Screen design** 

- [ ] Not complete yet? If I overlooked this, let me know.  Be sure your MVP stories are covered by the screens you design (at this point I would't recommend creating anything extra).  I'm looking for wireframes to understand the design.

**Time Log/Journal**

- [ ] Not complete yet? If I overlooked this, let me know. 


**Other**

- [ ] Missing link here: https://github.com/mad-ent-java-f23/student/blob/master/IndividualProjects.md

**Comment by pawaitemadisoncollege** [comment]
Hi @Kgrau1 - have you made the updates recommended above?

**Comment by Kgrau1** [comment]
I forgot about this but just went through and made some of the changes, I added a design directory and put the user stories, project plan, and screen design to it.

**Comment by pawaitemadisoncollege** [comment]
I see that you split them out - that helps with organization. If/when you address the other items I noted above and would like it reviewed, let me know.
